### ISSUE TITLE
Applied conventions on 9 repositories

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#829]
Hello,
    
`bincrafters-conventions` and `conan-readme-generator` were executed on the following repositories:

- [x] conan-freetype: stable/2.9.1 bincrafters/conan-freetype#28
- [x] conan-lcms: stable/2.9 bincrafters/conan-lcms#6
- [x] conan-libiconv: stable/1.15 bincrafters/conan-libiconv#14
- [x] conan-libjpeg: stable/9c bincrafters/conan-libjpeg#10
- [x] conan-libpng: stable/1.6.37 bincrafters/conan-libpng#26
- [x] conan-libtiff: stable/4.0.9 bincrafters/conan-libtiff#3
- [x] conan-libwebp: stable/1.0.0 bincrafters/conan-libwebp#8
- [x] conan-libxml2: stable/2.9.9 bincrafters/conan-libxml2#18
- [x] conan-lzma: stable/5.2.4 bincrafters/conan-lzma#17

###### auto-generated using conan-repo-actions

**Comment by madebr** [comment]
These are dependencies of imagemagick

**Comment by Croydon** [comment]
Please create pull request for the testing branches in the future. Otherwise we getting branches out of sync too easy

**Comment by Croydon** [comment]
Everything is merged.

I have synchronized the testing/ branches manually

**Comment by madebr** [comment]
@Croydon
Thanks, I'll remember to use testing branches.
