### ISSUE TITLE
Applied conventions on 9 repositories

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#856]
Hello,

`bincrafters-conventions` and `conan-readme-generator` were executed on the following repositories:

- [x] conan-libfdk_aac: testing/2.0.0 bincrafters/conan-libfdk_aac#4
- [x] conan-libmp3lame: testing/3.100 bincrafters/conan-libmp3lame#5
- [x] conan-libvpx: testing/1.8.0 bincrafters/conan-libvpx#4
- [x] conan-libx264: testing/20190605 bincrafters/conan-libx264#5
- [x] conan-libx265: testing/3.0 bincrafters/conan-libx265#8
- [x] conan-ogg: testing/1.3.3 bincrafters/conan-ogg#11
- [x] conan-openh264: testing/1.7.0 bincrafters/conan-openh264#4
- [x] conan-opus: testing/1.3.1 bincrafters/conan-opus#9
- [x] conan-vorbis: testing/1.3.6 bincrafters/conan-vorbis#14

These are dependencies of ffmpeg

**Comment by Croydon** [comment]
Everything which isn't merged yet did fail

**Comment by madebr** [comment]
@Croydon 
Thanks for the work!
I have updated the remaining pulls.

**Comment by SSE4** [comment]
all done
