### ISSUE TITLE
Applied conventions on 5 repositories

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#863]
Hello,

`bincrafters-conventions` was executed on the following repositories:

- [x] conan-libffi: testing/3.2.1 bincrafters/conan-libffi#5
- [x] conan-mpdecimal: testing/2.4.2 bincrafters/conan-mpdecimal#1
- [x] conan-libtirpc: testing/1.1.4 bincrafters/conan-libtirpc#3
- [x] conan-libnsl: testing/1.2.0 bincrafters/conan-libnsl#2
- [x] conan-sqlite3: testing/3.28.0 bincrafters/conan-sqlite3#26

Dependencies of cpython

**Comment by SSE4** [comment]
all done
